DistanceAlgorithm: Diamond # Circle, Diamond, Square (Recommend Diamond for best results, Circle is pretty intensive)
AllowAutoUpdates: false #If true this will auto download updates on server start and will take effect on next startup
VanillaMobEquipmentOverrides: true #If true, enchanted vanilla gear will override equipment settings in this file
MythicMobs:
  Enabled: true
  IgnoredWorlds:
  - world_the_end
SkillAPI:
  Enabled: false # if enabled, will use exp calculations for skillAPI
Heroes:
  Enabled: false # if enabled, will use exp calculations for skillAPI
  PartyExperienceFormulas:
    '2': "1.5 * {exp} / 2" # sets the amount of exp a player gets in a party
    '3': "1.8 * {exp} / 3"
    '4': "2.0 * {exp} / 4"
    '5': "2.2 * {exp} / 5"
    '6': "2.4 * {exp} / 6"
Names:
  TagsAlwaysOn: false # Do you want creature name tags to always show?
  Format: '[Lvl.{level}] {Variant} {name}' # Global name format, takes {level}, {Variant} or {variant}, {name}
SpawnPoints:
  world: # Name of the world spawnpoints are in
    mainTown: # name of spawnpoint
      Disabled: false # if the spawnpoint is disabled
      Level: 1 # starting level
      Distance: 50 # Interval to level up
      MaxLevel: -1 # -1 is disabled, but what level do mobs cap at for this spawn point?
      CenterBuffer: 50 # distance delay for creatures to not level up from the center
      Location: # The actual center point distance is calculated from
        X: 0
        Z: 0
    otherTown:
      Disabled: true
      Level: 20
      Distance: 100
      MaxLevel: 50
      CenterBuffer: 0
      Location:
        X: 10000
        Z: -5000
LevelRegions:
  world: # Name of the world the level regions are in
    undeadkeep: # name of the level region
      Level: 40 # level of all mobs in the region
      Names: # custom names for entities
        ZOMBIE: '&5Undead Warrior' # All zombies will have their name purple and be called 'Undead Warrior', accepts {level} tag
      Disabled: false
MobVariants:
  Disabled: true # Disable random variants?
  VariantChance: 40 # Chance (out of 100) for a mob to be variant
  DisabledTypes: #Disable variants for entire entity types
  - CREEPER
  Blinding:
    Disabled: false # Disable specific variants
    DisabledTypes: []
    Weight: 10 # The chance this variant is selected
    Blinding: # Effect details
      Duration: 60 # Blinding duration in ticks (1 second = 20 ticks)
      Level: 2 # potion effect level
      Chance: 100.0 # chance to blind on hit
  Burning:
    Disabled: false
    DisabledTypes: []
    Weight: 10
    DefensiveBurn:
      Ticks: 20
      Chance: 20.0
  Fast:
    Disabled: false
    DisabledTypes: []
    Weight: 10
    SpeedMultiplier: 1.5
  Glowing:
    Disabled: false
    DisabledTypes: []
    Weight: 10
  Invisible:
    Disabled: false
    DisabledTypes: []
    Weight: 10
  Poisonous:
    Disabled: false
    DisabledTypes: []
    Weight: 10
    Poison:
      Duration: 60
      Level: 0
      Chance: 20.0
  Slow:
    Disabled: false
    DisabledTypes: []
    Weight: 10
    SpeedMultiplier: 0.5
  Strong:
    Disabled: false
    DisabledTypes: []
    Weight: 10
    Damage: 2
    DamageMultiplier: 1.0
  Tough:
    Disabled: false
    DisabledTypes: []
    Weight: 10
    Armor: 2
    ArmorMultiplier: 1.0
Entity:
  Animal:
    Disabled: true
  Misc:
    Disabled: true
  Monster:
    Disabled: false # Can disabled full groups
    ZOMBIE:
      Disabled: false # Can disabled certain entities
      Formulas: # Formulas used to calculate different attributes. {level} allows for level based calculation
        Damage: rand(3) + ({level} / 10)
        Health: 20 + ({level} / 3) + ({level} / 5) + rand(5)
        Experience: rand(3) + 1
      Equipment: # Equipment given when entity is spawned
        Weapon:
          '1': RAW_FISH 10% drop:15%, WOOD_SWORD 10%, WOOD_AXE 10% # MATERIAL equip% drop:drop%, etc
          '12': STONE_SWORD 25%, STONE_AXE 20%
          '20': IRON_SWORD 30%, IRON_AXE 25%
          '30': GOLD_SWORD 35%, GOLD_AXE 30%
          '40': DIAMOND_SWORD 35%, DIAMOND_AXE 30%
        Offhand:
          '20': SHIELD 10%
          '40': SHIELD 15%
        Helmet:
          10: LEATHER_HELMET #If no equip% is provided it defaults to 100%
          20: CHAINMAIL_HELMET #If no drop% is provided it defaults to 0%
        Chestplate:
          12: LEATHER_CHESTPLATE
          22: CHAINMAIL_CHESTPLATE
        Leggings:
          14: LEATHER_LEGGINGS
          24: CHAINMAIL_LEGGINGS
        Boots:
          12: LEATHER_BOOTS
          22: CHAINMAIL_BOOTS
      Names: # Names given to the entity at certain milestones
        '1':
          Name: Weak Zombie
        '20':
          Name: Zombie
        '40':
          Name: Strong Zombie