name: LorinthsRpgMobs
main: me.Lorinth.LRM.LorinthsRpgMobs
version: 1.2.7
softdepend: [WorldGuard, Heroes, SkillAPI, MythicMobs, MythicDrops]
description: A plugin that provides configurable settings for creatures
commands:
  lrm:
    description: Accesses most configurable settings for Lorinths Rpg Mobs
    permission: lrm.admin