name: LorinthsRpgMobs
main: me.Lorinth.LRM.LorinthsRpgMobs
version: 0.8.5
description: A plugin that provides configurable settings for creatures
commands:
  lrm:
    description: Accesses most configurable settings for Lorinths Rpg Mobs
    permission: lrm.admin