name: LorinthsRpgMobs
main: me.Lorinth.LRM.LorinthsRpgMobs
version: 0.9.0
softdepend: [WorldGuard]
description: A plugin that provides configurable settings for creatures
commands:
  lrm:
    description: Accesses most configurable settings for Lorinths Rpg Mobs
    permission: lrm.admin